# Generated by Django 4.0.6 on 2022-07-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('balance', models.IntegerField()),
                ('freeze_type', models.BooleanField(default=False)),
                ('hold', models.BooleanField(default=False)),
            ],
        ),
    ]
